name: Build and Push Hockey RSVP Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

    - name: Build and push image
      run: |
        IMAGE_REPO="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

        # Build image
        podman build -t ${IMAGE_REPO}:latest .

        # Tag with branch and commit SHA
        podman tag ${IMAGE_REPO}:latest ${IMAGE_REPO}:${{ github.ref_name }}
        podman tag ${IMAGE_REPO}:latest ${IMAGE_REPO}:${{ github.ref_name }}-${{ github.sha }}

        # Push all tags
        podman push ${IMAGE_REPO}:latest
        podman push ${IMAGE_REPO}:${{ github.ref_name }}
        podman push ${IMAGE_REPO}:${{ github.ref_name }}-${{ github.sha }}