name: Deploy Hockey RSVP Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy bot
      run: |
        # Stop current container
        podman-compose down || true
        
        # Copy .env file from main repo directory
        if [ -f /home/silmser/home_repos/hockey-rsvp-bot/.env ]; then
          cp /home/silmser/home_repos/hockey-rsvp-bot/.env .env
          echo "✅ Copied .env file from main repo"
        else
          echo "❌ .env file not found in main repo directory!"
          echo "Please create /home/silmser/home_repos/hockey-rsvp-bot/.env from .env.example"
          exit 1
        fi
        
        # Rebuild container with latest code
        podman build -t hockey-rsvp-bot .
        
        # Start container
        podman-compose up -d
        
        # Check if container started successfully
        sleep 5
        if podman ps | grep -q hockey-rsvp-bot; then
          echo "✅ Deployment successful - Bot is running"
        else
          echo "❌ Deployment failed - Container not running"
          podman logs hockey-rsvp-bot
          exit 1
        fi